# General generation #
aether_height: 220
aether_spawnrate: 0.2      # Noise threshold for generation
aether_frequency: 1.45     # Frequency of hills and valleys
aether_amplitude: 0.8421   # Height of hills and valleys
#aether_scale: 0.00332
aether_octaves: 7          # Additional higher-frequency randomness added to smooth things out

# Ore generation #
coal_chance: 500
coal_size: 7
iron_chance: 2000
iron_size: 5
gold_chance: 4000
gold_size: 4
lapis_chance: 4000
lapis_size: 2
redstone_chance: 4000
redstone_size: 4
diamond_chance: 10000
diamond_size: 3
emerald_chance: 6000
emerald_size: 1
dirt_chance: 900
dirt_size: 15
gravel_chance: 1900
gravel_size: 15

# Tree generation #
#general_tree_chance: 50
#bigtree_chance: 1000
#prefab_tree_normal_count: 4
#prefab_tree_pine_count: 4
#prefab_tree_jungle_count: 3
#prefab_tree_birch_count: 4

# Cave generation #
#cave_rarity: 3
#cave_frequency: 35
#cave_min_y: 1
#cave_max_y: 200
#cave_individual_rarity: 20
#cave_pocket_chance: 3
#cave_radius_multiplier: 1.1

# Dungeon generation #
#dungeon_chance: 10
#prefab_dungeon_count: 2

# ? #
#generate_additional_features: true
#aether_goodies: true
