aether: true
prefab_tree_normal_count: 4
prefab_tree_pine_count: 4
prefab_tree_jungle_count: 3
prefab_tree_birch_count: 4
prefab_dungeon_count: 2
generate_additional_features: true
generate_coal: true
coal_chance: 500
coal_amount: 7
bigtree_chance: 1000
generate_iron: true
iron_chance: 2000
iron_amount: 5
generate_lapis: true
lapis_chance: 4000
lapis_amount: 2
generate_redstone: true
redstone_chance: 4000
redstone_amount: 4
generate_diamonds: true
diamond_chance: 10000
diamond_amount: 3
generate_emeralds: true
emerald_chance: 6000
emerald_amount: 1
generate_gold: true
gold_chance: 4000
gold_amount: 4
generate_dirt: true
dirt_chance: 900
dirt_amount: 15
generate_gravel: true
gravel_chance: 1900
gravel_amount: 15
cave_rarity: 3
dungeon_chance: 10
cave_frequency: 35
cave_min_y: 1
cave_max_y: 200
cave_individual_rarity: 20
cave_pocket_chance: 3
cave_radius_multiplier: 1.1
aether_height: 60
aether_goodies: true
aether_2_height: 40
aether_spawnrate: 0.2
aether_2_spawnrate: 0.01
aether_frequeny: 1.45
aether_amplitude: 0.8421
aether_2_amplitude: 0.95
aether_octaves: 7
aether_2_octaves: 7
aether_scale: 0.00332
aether_2_scale: 0.00587
aether_2: false
aether_2_frequency: 1.415
aether_frequency: 1.5024
general_tree_chance: 50
